# Travis CI build file for Swift gRPC.

# Use Ubuntu 14.04
dist: trusty

sudo: false

addons:
  apt:
    packages:
    - clang-3.8 
    - lldb-3.8 
    - libicu-dev 
    - libtool 
    - libcurl4-openssl-dev 
    - libbsd-dev 
    - build-essential 
    - libssl-dev 
    - uuid-dev
    - curl
    - unzip

install: ./.travis-install.sh

script: 
  - export PATH=.:$HOME/local/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/local/lib
  - make test
  - cd Plugin
  - make test
